name = "heimdall"
main = "src/worker.js"
compatibility_date = "2024-04-18"

kv_namespaces = [
  { binding = "STATUS_KV", id = "c679605aec604893b414c9df3451f4c5" }
]

triggers = { crons = ["*/5 * * * *"] }

[observability]
enabled = true

[env.staging.observability]
enabled = true
